/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        brand:          'var(--color-brand)',
        'brand-deep':   'var(--color-brand-deep)',
        'brand-deep2':  'var(--color-brand-deep2)',
        'brand-text':   'var(--color-brand-text)',
        'brand-ink':    'var(--color-brand-ink)',
        ink:            'var(--color-ink)',
        body:           'var(--color-body)',
        text2:          'var(--color-text2)',
        muted:          'var(--color-muted)',
        canvas:         'var(--color-canvas)',
        'canvas-alt':   'var(--color-canvas-alt)',
        surface:        'var(--color-surface)',
        'surface-tint': 'var(--color-surface-tint)',
        'tint-neutral': 'var(--color-tint-neutral)',
        hairline:       'var(--color-hairline)',
        'field-border': 'var(--color-field-border)',
        'header-line':  'var(--color-header-line)',
        success:        'var(--color-success)',
        warn:           'var(--color-warn)',
        'warn-strong':  'var(--color-warn-strong)',
        'warn-bg':      'var(--color-warn-bg)',
        'warn-border':  'var(--color-warn-border)',
        alert:          'var(--color-alert)',
        'alert-strong': 'var(--color-alert-strong)',
        'alert-bg':     'var(--color-alert-bg)',
        notify:         'var(--color-notify)',
      },
      fontFamily: {
        serif: ['Newsreader', 'Georgia', 'serif'],
        sans:  ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        mono:  ['Spline Sans Mono', 'monospace'],
      },
      maxWidth: {
        content: '1320px',
        wide:    '1080px',
        mid:     '980px',
        narrow:  '760px',
        thin:    '720px',
        form:    '400px',
      },
      keyframes: {
        marquee: {
          from: { transform: 'translateX(0)' },
          to:   { transform: 'translateX(-50%)' },
        },
        cross: {
          '0%,42%':   { opacity: '1' },
          '50%,92%':  { opacity: '0' },
          '100%':     { opacity: '1' },
        },
        cross2: {
          '0%,42%':   { opacity: '0' },
          '50%,92%':  { opacity: '1' },
          '100%':     { opacity: '0' },
        },
        scan: {
          '0%':   { top: '4%' },
          '50%':  { top: '92%' },
          '100%': { top: '4%' },
        },
        fadeup: {
          from: { opacity: '0', transform: 'translateY(14px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        pulsedot: {
          '0%,100%': { opacity: '1', transform: 'scale(1)' },
          '50%':     { opacity: '.35', transform: 'scale(.7)' },
        },
        bar: { from: { width: '0' } },
        float: {
          '0%,100%': { transform: 'translateY(0)' },
          '50%':     { transform: 'translateY(-7px)' },
        },
        rotatez: { to: { transform: 'rotate(360deg)' } },
      },
      animation: {
        marquee:      'marquee 34s linear infinite',
        cross:        'cross 7s ease-in-out infinite',
        cross2:       'cross2 7s ease-in-out infinite',
        scan:         'scan 1.6s ease-in-out infinite',
        fadeup:       'fadeup 0.7s ease both',
        'fadeup-slow':'fadeup 0.9s ease both',
        pulsedot:     'pulsedot 1.6s infinite',
        bar:          'bar 1.1s ease',
        'bar-slow':   'bar 1.3s ease',
        float:        'float 3s ease-in-out infinite',
        spinner:      'rotatez 0.9s linear infinite',
      },
    },
  },
  plugins: [],
};
